(lang dune 3.20)
(name shen-ocaml)
(generate_opam_files true)
(using menhir 2.1)
(package
 (name shen-ocaml)
 (synopsis "Shen Language port to OCaml")
 (description "A performant port of Shen to OCaml 5.")
 (allow_empty)
 (depends
  (ocaml (>= 5.3.0))
  (dune (>= 3.20))))
