(lang dune 3.14)
(name shen-ocaml)
(generate_opam_files true)
(package
 (name shen-ocaml)
 (synopsis "Shen Language port to OCaml")
 (description "A performant port of Shen to OCaml 5.")
 (allow_empty)
 (depends
  (ocaml (>= 4.14))
  (dune (>= 3.14))))
